import type {Metadata} from 'next';import Link from 'next/link';
export const metadata:Metadata={title:'Pricing · Energy Intelligence Global',description:'Plans for evidence-led renewable energy decisions, from a free evaluation to governed enterprise rollouts.'};
const tiers=[
{name:'Evaluation',price:'$0',period:'forever',tagline:'Validate one project workflow before procurement.',features:['3 AI interactions per day','2 resource queries and calculations per day','1 active project','7-day data retention'],cta:'Start free',href:'/assessment'},
{name:'Professional',price:'$29',period:'per month',tagline:'For analysts developing reviewable investment cases.',features:['100 AI interactions per day','Unlimited resource queries and calculations','Literature search and citation tools','PDF and Word export'],cta:'Start assessment',href:'/assessment'},
{name:'Operations',price:'$45',period:'per month',tagline:'For teams reviewing real plant and maintenance data.',features:['Maintenance diagnosis workflow','Up to 10 stations','100 AI interactions per day','PDF export'],cta:'Start assessment',href:'/assessment'},
{name:'Complete',price:'$59',period:'per month',tagline:'Planning and operations in one governed workspace.',features:['Professional and Operations capabilities','Up to 200 projects and 50 stations','PDF, Word, and Excel export','Priority response'],cta:'Start assessment',href:'/assessment',highlight:true},
{name:'Team',price:'$1,490',period:'per year',tagline:'For a five-person project or advisory team.',features:['5 team accounts','Shared projects and review workflow','Team-level usage allocation','PDF, Word, and Excel export'],cta:'Start assessment',href:'/assessment'},
{name:'Enterprise',price:'Custom',period:'annual agreement',tagline:'For governed integrations and multi-team rollouts.',features:['Enterprise roles and controls','API, SSO, and white-label options','Contract-defined scale and retention','Private deployment assessment'],cta:'Contact sales',href:'mailto:sales@aurenix-ai.com'}];
export default function Pricing(){return <main className="shell"><div className="eyebrow">Pricing</div><h1>Pay for decisions you can defend.</h1><p>Every plan keeps assumptions, source dates, and confidence notes visible. Prices in USD; annual billing available on monthly plans at two months free. Upgrade, downgrade, or cancel at any time.</p><div className="grid pricing-grid">{tiers.map(t=><article className={`card plan${t.highlight?' featured':''}`} key={t.name}>{t.highlight&&<span className="badge">Most popular</span>}<h2>{t.name}</h2><div className="metric">{t.price}</div><p className="period">{t.period}</p><p>{t.tagline}</p><ul>{t.features.map(f=><li key={f}>{f}</li>)}</ul>{t.href.startsWith('mailto:')?<a className={`button${t.highlight?'':' secondary'}`} href={t.href}>{t.cta}</a>:<Link className={`button${t.highlight?'':' secondary'}`} href={t.href}>{t.cta}</Link>}</article>)}</div><section><h2>Before you buy</h2><div className="grid"><article className="card"><h3>Assumptions stay visible</h3><p>No plan hides the inputs behind a result. Reviewers see the same evidence you do.</p></article><article className="card"><h3>Human review required</h3><p>Screening outputs support—not replace—bankable measurement and engineering judgment.</p></article><article className="card"><h3>Your data, retained by plan</h3><p>Data retention follows the plan you choose, from 7 days on Evaluation to contract terms on Enterprise.</p></article></div></section></main>}
