apiVersion: v1
kind: Service
metadata:
  name: financial-service
  labels:
    app: financial-service
spec:
  selector:
    app: financial-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
