#!/usr/bin/env python3
"""Generate the domestic-only topology from the shared runtime contract."""
from pathlib import Path
import argparse
import copy
import yaml

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'runtime/docker-compose.cn.production.yml'
CADDY = ROOT / 'runtime/Caddyfile.cn'


def domestic_config(source):
    config = copy.deepcopy(source)
    config['name'] = 'energy-intelligence-cn'
    config['services'].pop('web-int')
    gateway = config['services']['gateway']
    gateway['environment'].pop('INT_DOMAIN')
    gateway['depends_on'].pop('web-int')
    gateway['volumes'] = [mount.replace('./Caddyfile:', './Caddyfile.cn:') for mount in gateway['volumes']]
    # 国内部署不注入国际支付与海外模型凭据。
    environment = config['services']['backend']['environment']
    for key in ('OPENAI_API_KEY', 'ANTHROPIC_API_KEY', 'OPENROUTER_API_KEY', 'STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SECRET', 'SENDGRID_API_KEY'):
        environment.pop(key, None)
    return config


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    source = yaml.safe_load((ROOT / 'runtime/docker-compose.production.yml').read_text())
    config = domestic_config(source)
    caddy_source = (ROOT / 'runtime/Caddyfile').read_text()
    caddy = caddy_source.split('\n{$INT_DOMAIN} {', 1)[0].rstrip() + '\n'
    if args.check:
        if not TARGET.exists() or yaml.safe_load(TARGET.read_text()) != config:
            raise SystemExit('国内 Compose 已偏离主配置，请重新生成并审核')
        if not CADDY.exists() or CADDY.read_text() != caddy:
            raise SystemExit('国内网关已偏离主配置，请重新生成并审核')
        print('国内五服务拓扑与网关一致性检查通过')
    else:
        TARGET.write_text('# Generated by scripts/render_cn_compose.py; review changes before deployment.\n' + yaml.safe_dump(config, allow_unicode=True, sort_keys=False))
        CADDY.write_text(caddy)

if __name__ == '__main__':
    main()
